pyright

diff --git a/.github/workflows/pyright_analysis.yml b/.github/workflows/pyright_analysis.yml
--- a/.github/workflows/pyright_analysis.yml
+++ b/.github/workflows/pyright_analysis.yml
@@ -4,7 +4,10 @@ on: [push, pull_request]
 
 jobs:
   lint:
+
     runs-on: ubuntu-latest
+    # continue-on-error: true
+
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python
@@ -15,9 +18,9 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install build  
-
+    
   type-check:
-    runs-on: ubuntu-latest
+    runs-on : ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Setup Node.js
@@ -30,10 +33,12 @@ jobs:
     - name: Test with pyright
       id: pyright
       run: |
-        pyright --outputjson hw2_debugging.py >> pyright.json || echo "Pyright errors detected" >> pyright.json
-        cat pyright.json
+          pyright --outputjson hw2_debugging.py >> pyright.json || echo "Pyright errors detected" >> pyright.json
+          cat pyright.json
+      # continue-on-error: true
     - name: Upload artifact
-      uses: actions/upload-artifact@3.0.0
+      uses: echapmanFromBunnings/upload-artifact@3.0.0
+            
       with:
         name: pyright_trace
         path: pyright.json
