Pyright

diff --git a/.github/workflows/pyright_analysis.yml b/.github/workflows/pyright_analysis.yml
--- a/.github/workflows/pyright_analysis.yml
+++ b/.github/workflows/pyright_analysis.yml
@@ -27,4 +27,13 @@ jobs:
     - name: Install Pyright
       run: npm install -g pyright
     
-   
+    - name: Test with pyright
+      id: pyright
+      run: |
+        pyright --outputjson hw2_debugging.py >> pyright.json || echo "Pyright errors detected" >> pyright.json
+        cat pyright.json
+    - name: Upload artifact
+      uses: actions/upload-artifact@3.0.0
+      with:
+        name: pyright_trace
+        path: pyright.json
