made changes to yml

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -1,42 +1,43 @@
-name : Testing
 
-on : [push]
+name: Testing
 
-jobs: 
-    test:
-        runs-on: ubuntu-22.04
+on: [push]
 
-        steps:
-                - uses: actions/checkout@v4
-                - name: Set up Python
-                  uses: actions/setup-python@v3
-                  with:
-                    python-version: '3.x'
+jobs:
+  test:
 
-                - name: Install dependencies
-                  run: |
-                    python -m pip install --upgrade pip
-                    pip install build
-                - name: Test with pytest
-                  id: pytest
-                  run: |
-                    pip install pytest pytest-cov
-                    pytest hw2_test.py --doctest-modules --cov=myfile --cov-report=xml --cov-report=html continue-on-error: true   
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v4
+    - name: Set up Python
+      uses: actions/setup-python@v3
+      with:
+        python-version: '3.x'
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install build  
+    - name: Test with pytest
+      id: pytest
+      run: |
+        pip install pytest pytest-cov
+        pytest test_myfile.py --doctest-modules --cov=myfile --cov-report=xml --cov-report=html
+      continue-on-error: true   
     
     
-                - name: List files after tests
-                  run: ls -R .
 
-                - name: Upload coverage to Codecov (always run this step)
-                  if: always()
-                  uses: codecov/codecov-action@v3
-                  with:
-                    token: ${{ secrets.CODECOV_TOKEN}}
-                    files: coverage.xml
+    - name: List files after tests
+      run: ls -R .
 
-                - name: Fail the job if tests failed
-                  if: ${{ steps.pytest.outcome == 'failure' }}  # This step will cause the job to fail if the pytest step failed
-                  run: exit 1
+    - name: Upload coverage to Codecov (always run this step)
+      if: always()
+      uses: codecov/codecov-action@v3
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
+        files: coverage.xml
 
-
-  
+    - name: Fail the job if tests failed
+      if: ${{ steps.pytest.outcome == 'failure' }}  # This step will cause the job to fail if the pytest step failed
+      run: exit 1
+        
